

class Timer:

    PIXEL_PER_METER = (100.0 / 1)
    RUN_SPEED_KMPH = 60.0
    RUN_SPEED_MPM =  (RUN_SPEED_KMPH * 1000.0 / 60.0)
    RUN_SPEED_MPS = (RUN_SPEED_MPM / 60.0)
    RUN_SPEED_PPS = (RUN_SPEED_MPS + PIXEL_PER_METER)

    